export const LOAD_SET = 'LOAD_SET';
export const LOAD_POKEMON = 'LOAD_POKEMON';
export const LOAD_SET_SUCCESS = 'LOAD_SET_SUCCESS';
export const LOAD_SET_FAILURE = 'LOAD_SET_FAILURE';
export const LOAD_POKEMON_SUCCESS = 'LOAD_POKEMON_SUCCESS';
export const LOAD_POKEMON_FAILURE = 'LOAD_POKEMON_FAILURE';
